# Generated by Django 4.2.11 on 2024-03-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
