# Generated by Django 4.2.11 on 2024-03-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_log_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='message',
        ),
    ]
