# Generated by Django 4.2.11 on 2024-03-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_log_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='body',
            new_name='request_body',
        ),
        migrations.AddField(
            model_name='log',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
